### ISSUE TITLE
Make Graphs.jl a dependency.

### ISSUE THREAD

**Issue by twadleigh** [JuliaGeometry/OldMeshes.jl#10]
I'm looking to revisit getting the simplification algorithm working. In the process, I'm also going to entertain all manner of changes to the implementation.

One of them is to consider is re-basing the data structures on the relevant bits in Graphs.jl.

**Comment by sjkelly** [comment]
I currently have an implementation for non-topological mesh slicing. I will probably need Graphs.jl  for topological slicing. I will take a look at the simplification algorithm once I bring in Graphs.jl.
