### ISSUE TITLE
File Format Wishlist

### ISSUE THREAD

**Issue by sjkelly** [JuliaGeometry/OldMeshes.jl#24]
These would be nice to have for at least import. I think that supporting these will help establish the bounds on what considerations we will have to take for an improved `Mesh` type.
- [ ] [X3D](http://en.wikipedia.org/wiki/X3D)
- [ ] [3DS](http://en.wikipedia.org/wiki/.3ds)
- [ ] [DAE](https://en.wikipedia.org/wiki/COLLADA)

**Comment by jaakkor2** [comment]
I wrote rudimentary import and export for three.js JSON format described here
https://github.com/mrdoob/three.js/wiki/JSON-Model-format-3

JSON format can have morphtargets.  Morph targets are sets of geometry vertices positions for automatic interpolation between them.  I would like to support import and export of morphtargets that could look like Mesh-structure vertices. See for example

http://threejs.org/examples/webgl_morphtargets_horse
http://threejs.org/examples/models/animated/horse.js

Question: should morphtargets
a) be included in Mesh-type?
b) be passed by the io-functions as an array of Mesh-types? How to modify the function definitions (input arguments and return values then?

Another question: I would like to support volumes like amf-format does as an array of Mesh-types. If there is only one volume and then only one mesh, should I return "msh" or "[msh]", where msh is of type Mesh ?

**Comment by sjkelly** [comment]
@jaakkor2 this looks great. We are currently discussing how to get arbitrary data in the mesh type in issue #21. 

Returning an array of mesh is a poor solution. I only did this with AMF as a stop-gap solution to get the basic functionality in. Consistent return types will be necessary for 0.1.0.

**Comment by sjkelly** [comment]
Moved to MeshIO.
