### ISSUE TITLE
ERROR: no method procVox(...)

### ISSUE THREAD

**Issue by ryaninvents** [JuliaGeometry/OldMeshes.jl#26]
I tried to use Meshes.jl in a project and got an `ERROR: no method`. To make sure I was using the library correctly, I cloned the repo and ran `test_meshes.jl` from the master branch and got the same error.

```
ryan@bowdoin [07:53:54] [~/code/Meshes.jl/test] [master]
-> % julia test_meshes.jl 
ERROR: no method procVox(Array{Float64,1},Float64,Int32,Int32,Int32,Int32,Int32,Dict{Int64,Vector3{Float64}},Array{Face,1},Float64)
 in marchingTetrahedra at /home/ryan/.julia/v0.2/Meshes/src/isosurface.jl:241
 in isosurface at /home/ryan/.julia/v0.2/Meshes/src/isosurface.jl:250
 in isosurface at /home/ryan/.julia/v0.2/Meshes/src/isosurface.jl:267
 in include at boot.jl:238
 in include_from_node1 at loading.jl:114
 in process_options at client.jl:303
 in _start at client.jl:389
at /home/ryan/projects/Meshes.jl/test/test_meshes.jl:23
```

**Comment by sjkelly** [comment]
@baconscript it looks like you are on Julia 0.2, can you confirm with `versioninfo()`? Try updating to 0.3.

**Comment by sjkelly** [comment]
Oh hey Ryan! Didn't notice you changed your github handle. I like it!

**Comment by ryaninvents** [comment]
Haha thanks! I don't really juggle anymore so I figured it was time for a change.

Confirmed that I was on Julia v0.2.1 because I forgot to go to the PPA.
