### ISSUE TITLE
Mesh Repair

### ISSUE THREAD

**Issue by sjkelly** [JuliaGeometry/OldMeshes.jl#33]
I read some of admesh: https://github.com/admesh/admesh over the weekend. It is GPL, but has some good functionality and seems to be the mesh repair engine used by some popular 3D printing engines. I think it would be a good exercise to wrap it in Julia (easy since it is C). 

It should definitely be a separate package that bring in the Meshes types. In the long term, we should try and do a clean room implementation in this package.

**Comment by twadleigh** [comment]
Can you provide an academic reference or two? I might be willing to tackle it around the time I get back to trying to get simplification up and running (hopefully within the next few months).

**Comment by hroncok** [comment]
This is a thesis about ADMesh and what it does

http://www.varlog.com/admesh-htm/ADMeshThesis.zip

**Comment by sjkelly** [comment]
@hroncok thanks for sharing!
