### ISSUE TITLE
Center mesh preview in iJulia notebooks

### ISSUE THREAD

**Issue by ryaninvents** [JuliaGeometry/OldMeshes.jl#40]
Right now the meshes pivot around the origin. It would be easier to use if they pivoted around their center.

**Comment by ryaninvents** [comment]
I'll tackle this issue. Thought I'd be able to assign it to myself, but GitHub doesn't seem to be letting me.

**Comment by sjkelly** [comment]
:+1:  I have added you as a collaborator so you can assign yourself.

**Comment by sjkelly** [comment]
This has been moved to MeshIO, and it probably supplanted by ThreeJS.jl.
