### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by jminardi** [JuliaGeometry/OldMeshes.jl#47]
The latest commit broke our codebase. If version numbers were used we could specify which version we depend on.

**Comment by sjkelly** [comment]
Yes, master is targeting 0.4 and the GLVisualize infrastructure, so it is highly unstable. The current work is to switch to GeometryTypes and integrate the MeshesIO API. I can go back and tag a safe 0.3 release if that is what you need, or a release prior to the breakage you noticed.

**Comment by sjkelly** [comment]
I tagged a 0.1.0 release, pending publication: https://github.com/JuliaLang/METADATA.jl/pull/2724

Again, sorry for breaking the API. The breakage is relatively minor compared to what is on a couple of my branches right now ;). 

As I mentioned, master will target `julia 0.4-` so I have made a branch for the `v0.1.x` series so we can submit bug fixes, and so this API can stay frozen.
https://github.com/JuliaGeometry/Meshes.jl/tree/v0.1.x

CC @dreammaker

P.S. Hope y'all Voxel8rs are doing well, and see you soon at JuliaCon!

**Comment by jminardi** [comment]
Thanks!

On Tue, Jun 9, 2015 at 2:16 PM, Steve Kelly notifications@github.com
wrote:

> I tagged a 0.1.0 release, pending publication: JuliaLang/METADATA.jl#2724
> https://github.com/JuliaLang/METADATA.jl/pull/2724
> 
> Again, sorry for breaking the API. The breakage is relatively minor
> compared to what is on a couple of my branches right now ;).
> 
> As I mentioned, master will target julia 0.4- so I have made a branch for
> the v0.1.x series so we can submit bug fixes, and so this API can stay
> frozen.
> https://github.com/JuliaGeometry/Meshes.jl/tree/v0.1.x
> 
> CC @dreammaker https://github.com/dreammaker
> 
> P.S. Hope y'all Voxel8rs are doing well, and see you soon at JuliaCon!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JuliaGeometry/Meshes.jl/issues/47#issuecomment-110453307
> .

## 

Jack Minardi
jack.minardi.org
jack@minardi.org

**Comment by sjkelly** [comment]
It should be tagged now. See NEWS.MD for notable API changes.
