### ISSUE TITLE
Julia-0.2-rc fails to import Meshes

### ISSUE THREAD

**Issue by dmbates** [JuliaGeometry/OldMeshes.jl#7]
``` jl
julia> versioninfo()
Julia Version 0.2.0-rc1+151
Commit 4074c96 2013-10-25 13:51:55 UTC
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm

julia> using Meshes
ERROR: MarchingTetrahedra not found
 in require at loading.jl:44
 in include at boot.jl:238
at /home/bates/.julia/Meshes/src/Meshes.jl:4
```

I think the easiest fix is to not have MarchingTetrahedra in its own module.

I can test the change and create a pull request if you wish.  Just let me know if you want me to do that.

**Comment by twadleigh** [comment]
@dmbates, if you'd like to create a pull request, I'd be happy to accept it, but I should have some time next week to revisit this project and get it into a form that matches the current standard for packages.

My need for this functionality dissipated a few months ago, so I'm afraid I've left it to bit rot for a while. However, there is a sufficient kernel of usefulness that it might be worth the effort to bring it up to date...

**Comment by twadleigh** [comment]
dc51058981ded32880907818e892f5a629f4b0c2 addresses this. I've tagged this and will generate a pull request to julia/METADATA.jl.
