### ISSUE TITLE
Archive?

### ISSUE THREAD

**Issue by twadleigh** [JuliaGeometry/OldMeshes.jl#72]
It looks like all the interesting stuff here has migrated to [Meshing.jl](https://github.com/JuliaGeometry/Meshing.jl) and this package has been removed from the registry.

If there are no objections, I will archive this repo in the next 24 hours.

**Comment by sjkelly** [comment]
What was the status of the simplification code?

**Comment by sjkelly** [comment]
I agree with the archiving. RIP. This was the genesis of so many packages Meshing, GeometryTypes, MeshIO. Thanks @twadleigh!

**Comment by twadleigh** [comment]
I recall I ran into unexpected failures when I was testing what I had written. Assuming no one has touched it since I originally wrote what was there, it is still bug-riddled. And it has remained so because I haven't had any personal need for it. If the need ever arises, the code can be copied and pasted from here as a starting point.

**Comment by twadleigh** [comment]
BTW, I renamed the repo to free up the Meshes.jl name.
